services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: seo-plugin-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress-network

  # WordPress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: seo-plugin-wordpress
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress_data:/var/www/html
      - ./:/var/www/html/wp-content/plugins/seo-optimizer:rw
    networks:
      - wordpress-network

  # WP-CLI - Separate service for CLI commands
  wpcli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    container_name: seo-plugin-wpcli
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./:/var/www/html/wp-content/plugins/seo-optimizer:rw
    networks:
      - wordpress-network
    user: "33:33"

  # phpMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    container_name: seo-plugin-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - wordpress-network

volumes:
  wordpress_data:
  db_data:

networks:
  wordpress-network:
    driver: bridge